import type { Capability, CapabilityCandidate, CapabilityDomain, CapabilityModel } from "./contracts.js";

export interface CapabilitiesMarkdownOptions {
  /** Render include_with_qualification capabilities under "Available with limitations". Recommended default: on. */
  includePartial: boolean;
  /** Render gap_only capabilities under "Known capability gaps". Recommended default: on. */
  includeGaps: boolean;
  /** Render roadmap_only capabilities under an opt-in "Roadmap" section. Recommended default: off. */
  includeRoadmap: boolean;
  /** Render excluded candidates under an opt-in "Excluded candidates" diagnostics section. Recommended default: off. */
  includeExcluded: boolean;
}

export const DEFAULT_CAPABILITIES_MARKDOWN_OPTIONS: CapabilitiesMarkdownOptions = {
  includePartial: true,
  includeGaps: true,
  includeRoadmap: false,
  includeExcluded: false,
};

function evidenceLines(capability: Capability): string {
  if (capability.evidence.length === 0) return "_No evidence recorded._";
  return capability.evidence.map((e) => `- \`${e.sourcePath}\` — ${e.description} (${e.confidence})`).join("\n");
}

function capabilityBlock(capability: Capability, headingLevel: number): string {
  const h = "#".repeat(headingLevel);
  const lines: string[] = [];
  lines.push(`${h} ${capability.displayName}`);
  lines.push("");
  lines.push(`**Status:** ${capability.status} · **Confidence:** ${capability.confidence} · **Readiness:** ${capability.readiness.score}/100`);
  lines.push("");
  lines.push(`**Purpose:** ${capability.purpose}`);
  if (capability.outcome) {
    lines.push("");
    lines.push(`**Outcome:** ${capability.outcome}`);
  }
  if (capability.workflows.length > 0) {
    lines.push("");
    lines.push(`**Supporting workflows:** ${capability.workflows.length}`);
  }
  if (capability.actors.length > 0) {
    lines.push("");
    lines.push(`**Primary users:** ${capability.actors.join(", ")}`);
  }
  lines.push("");
  lines.push("**Evidence:**");
  lines.push(evidenceLines(capability));
  if (capability.readiness.blockers.length > 0 || capability.readiness.qualifiers.length > 0) {
    lines.push("");
    lines.push("**Known limitations:**");
    for (const b of capability.readiness.blockers) lines.push(`- ${b}`);
    for (const q of capability.readiness.qualifiers) lines.push(`- ${q}`);
  }
  lines.push("");
  return lines.join("\n");
}

function summaryTable(model: CapabilityModel): string {
  const rows = model.domains.map((d: CapabilityDomain) => {
    const excludedInDomain = model.excludedCandidates.filter((c) => c.domainId === d.id).length;
    const includedCount = d.capabilities.length - d.partialCapabilityCount;
    return `| ${d.displayName} | ${includedCount} | ${d.partialCapabilityCount} | ${excludedInDomain} |`;
  });
  return ["| Domain | Included | Partial | Excluded candidates |", "| --- | --- | --- | --- |", ...rows].join("\n");
}

/**
 * The generated document. §14: header carries a generation-provenance note;
 * every section below the summary table only ever draws from
 * include/include_with_qualification/gap_only/roadmap_only/exclude buckets
 * that the evidence-and-maturity gate already decided — this function makes
 * no inclusion judgment of its own, it only formats what synthesizeCapabilities()
 * already decided, gated by which opt-in sections the caller requested.
 */
export function exportCapabilitiesMarkdown(model: CapabilityModel, options: CapabilitiesMarkdownOptions = DEFAULT_CAPABILITIES_MARKDOWN_OPTIONS): string {
  const lines: string[] = [];

  lines.push(`# ${model.systemIdentity.displayName} — Capabilities`);
  lines.push("");
  lines.push(
    `> Generated by Repo Visual Studio's Capability Intelligence engine at ${model.generationMetadata.generated_at} from commit \`${model.generationMetadata.git_commit}\`. This document is derived entirely from repository evidence and a deterministic evidence/maturity gate — no external model was used to author or embellish it. Candidates without sufficient implementation, execution, and verification evidence are excluded from this document by design; see the machine-readable diagnostics for the full candidate set.`,
  );
  lines.push("");

  if (model.systemIdentity.purpose) {
    lines.push("## Platform purpose");
    lines.push("");
    lines.push(model.systemIdentity.purpose);
    lines.push("");
  }

  lines.push("## Capability summary");
  lines.push("");
  lines.push(summaryTable(model));
  lines.push("");

  lines.push("## Capability domains");
  lines.push("");
  for (const domain of model.domains) {
    lines.push(`### ${domain.displayName}`);
    lines.push("");
    if (domain.purpose) {
      lines.push(domain.purpose);
      lines.push("");
    }
    for (const capability of domain.capabilities.filter((c) => c.inclusion === "include")) {
      lines.push(capabilityBlock(capability, 4));
    }
  }

  if (options.includePartial && model.qualifiedCapabilities.length > 0) {
    lines.push("## Available with limitations");
    lines.push("");
    lines.push("The following capabilities provide real, evidence-backed value today, but execution, verification, or operational maturity work remains — they are qualified rather than presented as fully operational.");
    lines.push("");
    for (const capability of model.qualifiedCapabilities) lines.push(capabilityBlock(capability, 3));
  }

  if (options.includeGaps && model.gapCapabilities.length > 0) {
    lines.push("## Known capability gaps");
    lines.push("");
    lines.push("Repository evidence identifies the following as known, operationally meaningful absences rather than implemented capabilities.");
    lines.push("");
    for (const gap of model.gapCapabilities) {
      lines.push(`- **${gap.displayName}** — ${gap.gapStatement?.value ?? gap.purpose}`);
    }
    lines.push("");
  }

  if (options.includeRoadmap && model.roadmapCapabilities.length > 0) {
    lines.push("## Roadmap");
    lines.push("");
    lines.push("The repository itself identifies the following as planned or future work, not implemented today.");
    lines.push("");
    for (const item of model.roadmapCapabilities) {
      lines.push(`- **${item.displayName}** — ${item.roadmapStatement?.value ?? item.purpose}`);
    }
    lines.push("");
  }

  if (options.includeExcluded && model.excludedCandidates.length > 0) {
    lines.push("## Excluded candidates");
    lines.push("");
    lines.push("Machine-readable diagnostics: candidates discovered but excluded from the current-capability narrative, with reason codes.");
    lines.push("");
    lines.push("| Candidate | Status | Reason codes | Summary |");
    lines.push("| --- | --- | --- | --- |");
    for (const excluded of model.excludedCandidates) {
      lines.push(`| ${excluded.displayName} | ${excluded.status} | ${excluded.reasonCodes.join(", ") || "—"} | ${excluded.reasonSummary} |`);
    }
    lines.push("");
  }

  lines.push("## Evidence and generation metadata");
  lines.push("");
  lines.push(`- Schema version: ${model.generationMetadata.schema_version}`);
  lines.push(`- Generated at: ${model.generationMetadata.generated_at}`);
  lines.push(`- Git commit: \`${model.generationMetadata.git_commit}\``);
  lines.push(`- Source Architecture Intelligence generated at: ${model.generationMetadata.source_architecture_intelligence_generated_at}`);
  lines.push(`- External model used: ${model.generationMetadata.assist_used ? "yes" : "no"}`);
  lines.push(`- Candidates discovered: ${model.generationMetadata.candidateCount}`);
  lines.push(
    `- Disposition: ${model.evidenceSummary.includedCount} included, ${model.evidenceSummary.qualifiedCount} qualified, ${model.evidenceSummary.gapCount} gaps, ${model.evidenceSummary.roadmapCount} roadmap-only, ${model.evidenceSummary.excludedCount} excluded, ${model.evidenceSummary.unresolvedCount} unresolved.`,
  );
  lines.push(
    `- Confidence: ${model.evidenceSummary.confidence.confirmed} confirmed, ${model.evidenceSummary.confidence.derived} derived, ${model.evidenceSummary.confidence.suggested} suggested, ${model.evidenceSummary.confidence.unresolved} unresolved (of ${model.evidenceSummary.confidence.total}).`,
  );
  lines.push(`- Readiness thresholds: ${JSON.stringify(model.generationMetadata.readinessThresholds)}`);
  lines.push(`- Readiness weights: ${JSON.stringify(model.generationMetadata.readinessWeights)}`);
  lines.push("");

  return lines.join("\n");
}

export function exportCapabilityModelJson(model: CapabilityModel): string {
  return JSON.stringify(model, null, 2);
}

export function exportCapabilityCandidatesJson(candidates: CapabilityCandidate[]): string {
  return JSON.stringify(candidates, null, 2);
}

export function exportCapabilityExclusionsJson(model: CapabilityModel): string {
  return JSON.stringify(model.excludedCandidates, null, 2);
}
