import { rmSync } from "node:fs";
import type {
  CandidateGenerationMetadata,
  VisualArtifactType,
  VisualDeliveryOutcome,
} from "./contracts.js";
import { allocateRun, candidateAbsolutePath, pruneRuns, stageCandidate, RUN_RETENTION } from "./candidate.js";
import { readVerifiedHistory, withPromotion, writeVerifiedHistory } from "./history.js";
import { promoteCandidate, readTargetState } from "./promotion.js";
import { previewFor } from "./preview.js";
import {
  buildRepairReceipt,
  buildVerificationReport,
  writeRepairReceipt,
  writeVerificationReport,
} from "./receipts.js";
import { deliveryRoot, repoRelative } from "./security.js";
import { verifyCandidate, type VerifyCandidateInput } from "./verification.js";
import type { VerificationProfile } from "./validation-profile.js";

// The delivery decision, start to finish.
//
// Stage, verify, promote or preserve, record. The order is the whole safety
// property: nothing reaches the target before it has been measured, and
// nothing is written about what passed until the target actually holds it.
//
// This module renders nothing. The HTML arrives already generated by the
// command that owns that surface -- `rvs graph open`, `rvs graph review` --
// so there is exactly one renderer per artifact and this layer can never
// deliver a picture that differs from the one those commands produce.

export interface DeliverVisualArtifactInput
  extends Omit<VerifyCandidateInput, "candidate" | "profile"> {
  profile: VerificationProfile;
  artifact_type: VisualArtifactType;
  /** Where the artifact goes if it passes. Repository-relative or absolute inside the repository. */
  target_path: string;
  /** The generated artifact, exactly as its renderer produced it. */
  html: string;
  /** The fidelity receipt's source digest: what the drawing was made from. */
  source_digest: string;
  metadata: CandidateGenerationMetadata;
  /** The clock, supplied by the caller so nothing in this package reads it. Metadata only. */
  now: string;
  /** Finished run directories to keep. */
  run_retention?: number;
}

/**
 * Runs one candidate through the gate.
 *
 * Never throws for a validation outcome -- a rejected candidate is a result,
 * not an exception -- and never leaves the target in a state this function
 * cannot describe. A path that escapes the repository or the delivery root
 * does throw, before anything is written, because that is a caller mistake
 * rather than a measurement.
 */
export async function deliverVisualArtifact(
  input: DeliverVisualArtifactInput,
): Promise<VisualDeliveryOutcome> {
  const run = allocateRun(input.repoRoot);

  const candidate = stageCandidate({
    repoRoot: input.repoRoot,
    run,
    artifact_type: input.artifact_type,
    target_path: input.target_path,
    html: input.html,
    visual_spec_id: input.spec.id,
    source_digest: input.source_digest,
    validation_profile: input.profile.id,
    metadata: input.metadata,
    created_at: input.now,
  });

  const before = readTargetState(input.repoRoot, candidate.target_path);

  const result = await verifyCandidate({ ...input, candidate, profile: input.profile });
  const promotion = promoteCandidate({
    repoRoot: input.repoRoot,
    candidate,
    result,
    verified_at: input.now,
  });

  // The verified record is written only once the target actually holds the
  // verified bytes. Writing it before the rename would mean a failed rename
  // left a record claiming a promotion that did not happen -- and the record
  // is the thing every later run trusts.
  let lastKnownGood = before.verified;
  if (promotion.status === "promoted" && promotion.verified !== null) {
    const history = withPromotion(readVerifiedHistory(input.repoRoot, candidate.target_path), promotion.verified);
    writeVerifiedHistory(input.repoRoot, history);
    lastKnownGood = promotion.verified;
  }

  const report = buildVerificationReport({
    result,
    generated_at: input.now,
    target_path: candidate.target_path,
    digest_before: promotion.digest_before,
    digest_after: promotion.digest_after,
    promotion_status: promotion.status,
    promotion_reason: promotion.reason,
    last_known_good: lastKnownGood,
  });
  const reportPath = writeVerificationReport(input.repoRoot, run.directory, report);

  let receipt = null;
  let receiptPath: string | null = null;
  let receiptMarkdownPath: string | null = null;
  if (promotion.status !== "promoted") {
    receipt = buildRepairReceipt({
      repoRoot: input.repoRoot,
      result,
      candidate,
      target_preserved: promotion.target_preserved,
      target_digest: promotion.digest_after,
      last_known_good: lastKnownGood,
    });
    const written = writeRepairReceipt(input.repoRoot, run.directory, receipt);
    receiptPath = written.json;
    receiptMarkdownPath = written.markdown;
  }

  // Cleanup, once and deterministically. A promoted candidate is at the
  // target, so the staged copy is redundant and is removed. A rejected one is
  // kept -- the receipt has been written by this point, so the evidence is
  // already safe, and a person reading "rejected for an overflow in the
  // detail view" will want to open the file that overflowed.
  if (promotion.status === "promoted") {
    rmSync(candidateAbsolutePath(input.repoRoot, candidate), { force: true });
  }
  pruneRuns(input.repoRoot, input.run_retention ?? RUN_RETENTION, [run.run_id]);

  const after = readTargetState(input.repoRoot, candidate.target_path);

  return {
    result,
    promotion: promotion.status,
    promotion_reason: promotion.reason,
    verified: promotion.verified,
    last_known_good: lastKnownGood,
    target_path: candidate.target_path,
    target_digest_before: promotion.digest_before,
    target_digest_after: promotion.digest_after,
    receipt,
    receipt_path: receiptPath,
    receipt_markdown_path: receiptMarkdownPath,
    report_path: reportPath,
    preview: previewFor(
      input.repoRoot,
      candidate.target_path,
      result.status,
      promotion.status === "promoted",
      after.exists,
    ),
  };
}

/** The console lines a command prints after a delivery run. Short by design; the report holds the rest. */
export function deliveryConsoleLines(outcome: VisualDeliveryOutcome): string[] {
  const lines: string[] = [];
  const summary = outcome.result.validator_summary;
  lines.push(
    `Generated candidate ${outcome.result.candidate.candidate_id} (generation ${outcome.result.candidate.generation}).`,
  );
  lines.push(
    `Ran ${summary.checks_run} checks across ${summary.families.length} validator families under ${outcome.result.profile.id}.`,
  );

  if (outcome.promotion === "promoted") {
    lines.push(`Promoted verified artifact to ${outcome.target_path}.`);
  } else if (outcome.result.status === "incomplete") {
    lines.push(`Verification incomplete: ${outcome.result.incomplete_reason ?? "a required check could not run"}.`);
    lines.push(`Candidate not promoted. ${lastKnownGoodLine(outcome)}`);
  } else {
    lines.push(
      `${summary.findings_blocking} blocking finding${summary.findings_blocking === 1 ? "" : "s"}; candidate not promoted.`,
    );
    lines.push(lastKnownGoodLine(outcome));
  }

  if (outcome.receipt_path !== null) lines.push(`Receipt: ${outcome.receipt_path}`);
  lines.push(`Report: ${outcome.report_path}`);
  lines.push(
    outcome.preview.url === null
      ? `Preview: ${outcome.preview.status_label} — nothing is at ${outcome.target_path} yet.`
      : `Preview: ${outcome.preview.status_label} — ${outcome.preview.url}`,
  );
  return lines;
}

function lastKnownGoodLine(outcome: VisualDeliveryOutcome): string {
  if (outcome.last_known_good !== null) {
    return `Last known good preserved: ${outcome.target_path} (${outcome.last_known_good.verified_artifact_id}).`;
  }
  if (outcome.target_digest_after !== null) {
    return `An unverified artifact was already at ${outcome.target_path}; it was left exactly as it was.`;
  }
  return `Nothing has ever been verified at ${outcome.target_path}, and nothing was written there.`;
}

/** Repository-relative path of the delivery root, for a command that wants to name it. */
export function deliveryRootPath(repoRoot: string): string {
  return repoRelative(repoRoot, deliveryRoot(repoRoot));
}
